-- 022: the document registry.
--
-- Every document generated by services/documents/ is recorded here when it is
-- issued. Without this an issue number is decoration: it is printed on a page
-- that a buyer may quote back six months later, and nothing on our side can say
-- what that number refers to.
--
-- It also makes the playbook's "evidence packs issued" a real number rather
-- than an intention.
--
-- WHAT THIS DELIBERATELY DOES NOT DO
-- ---------------------------------
-- It does not track where a document went. The playbook rates a data
-- controversy as existential, and a producer mark that quietly reports back on
-- a client's file is exactly that controversy. There is no open tracking, no
-- callback, no per-recipient token. `forwarded_at` below is set only when a
-- client tells us they sent it — self-reported, never observed.
--
-- `content_sha256` gives the useful half of tracking without the harmful half:
-- someone holding a forwarded PDF can be told whether it is byte-for-byte the
-- document we issued under that number. Verification, not surveillance.

CREATE TABLE IF NOT EXISTS document_issues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

    kind TEXT NOT NULL,
    -- The quotable number, e.g. EP-2026-000143. Unique across the whole
    -- installation rather than per tenant: it gets read down a phone line, and
    -- two clients holding the same number would make it useless as a reference.
    issue_number TEXT NOT NULL UNIQUE,
    issue_year INTEGER NOT NULL,
    sequence INTEGER NOT NULL,

    -- What the document said about itself, captured at issue time. Stored
    -- rather than recomputed because the underlying data changes: a pack issued
    -- in August covered what it covered, whatever the fields look like in
    -- November. Recomputing would silently rewrite history.
    subject TEXT NOT NULL,
    coverage_start DATE,
    coverage_end DATE,
    hectares NUMERIC(12,2),

    content_sha256 TEXT NOT NULL,

    issued_by_user_id UUID REFERENCES profiles(id),
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Self-reported by the client. Never inferred.
    forwarded_at TIMESTAMP WITH TIME ZONE,
    forwarded_note TEXT
);

-- Allocation of the next sequence relies on this: the insert races, and the
-- loser retries with a higher number. Cheaper and clearer than a lock table.
CREATE UNIQUE INDEX IF NOT EXISTS idx_document_issues_kind_year_seq
    ON document_issues (kind, issue_year, sequence);

CREATE INDEX IF NOT EXISTS idx_document_issues_tenant
    ON document_issues (tenant_id, issued_at DESC);

CREATE INDEX IF NOT EXISTS idx_document_issues_hash
    ON document_issues (content_sha256);
